/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luizfrancisco.estacionamento.view;

import com.luizfrancisco.estacionamento.controller.ClienteController;
import com.luizfrancisco.estacionamento.controller.VeiculoController;
import com.luizfrancisco.estacionamento.dao.VeiculoDAO;
import com.luizfrancisco.estacionamento.model.Veiculo;
import com.luizfrancisco.estacionamento.model.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author npc12
 */
public class BuscarVeiculo extends javax.swing.JFrame {
    private Principal origem;
    private ClienteController cc = new ClienteController();
    private VeiculoController vc = new VeiculoController();
    private int linhaSelecionada = -1;
    /**
     * Creates new form BuscarVeiculo
     */
    public BuscarVeiculo() {
        initComponents();
    }
    
    public BuscarVeiculo(Principal origem) {
        initComponents();
        atualizarTabela("");
        this.origem = origem;
        setResizable(false); 
        setLocationRelativeTo(this);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisaVeiculo = new javax.swing.JTextField();
        btnSelecionarVeiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscarVeiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 543));

        txtPesquisaVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a Placa ou Código"));
        txtPesquisaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaVeiculoActionPerformed(evt);
            }
        });
        txtPesquisaVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaVeiculoKeyPressed(evt);
            }
        });

        btnSelecionarVeiculo.setText("Selecionar");
        btnSelecionarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarVeiculoActionPerformed(evt);
            }
        });

        tblBuscarVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Modelo", "Cor", "Nome Cliente"
            }
        ));
        jScrollPane1.setViewportView(tblBuscarVeiculos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelecionarVeiculo)
                    .addComponent(txtPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionarVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaVeiculoActionPerformed

    private void btnSelecionarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarVeiculoActionPerformed
        linhaSelecionada = tblBuscarVeiculos.getSelectedRow();
        if(linhaSelecionada > -1){
            
            int id;
            Object idObj = tblBuscarVeiculos.getValueAt(linhaSelecionada, 0);
            
            if(idObj instanceof Integer){
                id = (Integer) idObj;
            }else {
                id = Integer.parseInt(idObj.toString());
            }
            String placa = (String) tblBuscarVeiculos.getValueAt(linhaSelecionada, 1);
            String modelo = (String) tblBuscarVeiculos.getValueAt(linhaSelecionada, 2);
            String cor = (String) tblBuscarVeiculos.getValueAt(linhaSelecionada, 3);
            String nomeCliente = tblBuscarVeiculos.getValueAt(linhaSelecionada, 4).toString();

            Cliente cliente = new Cliente(); 
            cliente.setNome(nomeCliente);

            
            Veiculo v = new Veiculo(id, cliente, modelo, cor, placa);
            
                if (this.origem != null) {
                    this.origem.preencherVeiculo(v);
                }
                this.dispose();
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente na tabela.");
        }
    }//GEN-LAST:event_btnSelecionarVeiculoActionPerformed

    private void txtPesquisaVeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaVeiculoKeyPressed
        String buscar = txtPesquisaVeiculo.getText();
        // A cada tecla solta, a tabela é atualizada automaticamente
        atualizarTabela(buscar);
    }//GEN-LAST:event_txtPesquisaVeiculoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionarVeiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuscarVeiculos;
    private javax.swing.JTextField txtPesquisaVeiculo;
    // End of variables declaration//GEN-END:variables
private void atualizarTabela(String busca) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblBuscarVeiculos.getModel();
        model.setRowCount(0);

        try{
            List<Veiculo> veiculos = vc.filtrarVeiculos(busca);
            for (Veiculo v : veiculos) {
                model.addRow(new Object[]{
                    v.getId(),
                    v.getPlaca(),
                    v.getModelo(),
                    v.getCor(),
                    v.getCliente().getNome() 
                });
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, 
            "Erro ao carregar dados do veículo: " + e.getMessage(),
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
}
