/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luizfrancisco.estacionamento.view;

import com.luizfrancisco.estacionamento.controller.ClienteController;
import com.luizfrancisco.estacionamento.dao.ClienteDAO;
import com.luizfrancisco.estacionamento.model.Cliente;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author luizfkm
 */
public class BuscarClientes extends javax.swing.JFrame {
    private static final ClienteDAO cDAO = new ClienteDAO();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuscarClientes.class.getName());
    private Principal origem;
    private final ClienteController cc = new ClienteController();
    private int linhaSelecionada = -1;

    /**
     * Creates new form BuscarClientes
     */
    public BuscarClientes() {
        initComponents(); 
    }

    public BuscarClientes(Principal origem) {
        initComponents();
        atualizarTabela("");
        this.origem = origem;
        setLocationRelativeTo(this);
        setResizable(false); 
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPesquisarCliente = new javax.swing.JTextField();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscarClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtPesquisarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o nome ou código"));
        txtPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarClienteActionPerformed(evt);
            }
        });
        txtPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarClienteKeyPressed(evt);
            }
        });

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        tblBuscarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone"
            }
        ));
        tblBuscarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscarClientes);
        if (tblBuscarClientes.getColumnModel().getColumnCount() > 0) {
            tblBuscarClientes.getColumnModel().getColumn(0).setResizable(false);
            tblBuscarClientes.getColumnModel().getColumn(1).setResizable(false);
            tblBuscarClientes.getColumnModel().getColumn(2).setResizable(false);
            tblBuscarClientes.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSelecionar)
                    .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarClienteActionPerformed
        String buscar = txtPesquisarCliente.getText();
        atualizarTabela(buscar);
    }//GEN-LAST:event_txtPesquisarClienteActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        linhaSelecionada = tblBuscarClientes.getSelectedRow();
        if(linhaSelecionada > -1){
            int id;
            Object idObj = tblBuscarClientes.getValueAt(linhaSelecionada, 0);
            
            if(idObj instanceof Integer){
                id = (Integer) idObj;
            }else {
                id = Integer.parseInt(idObj.toString());
            }
            
            String nome = (String) tblBuscarClientes.getValueAt(linhaSelecionada, 1);
            String email = (String) tblBuscarClientes.getValueAt(linhaSelecionada, 2);
            String telefone = (String) tblBuscarClientes.getValueAt(linhaSelecionada, 3);
            
            Cliente c = new Cliente(id, nome, email, telefone);
            
                if (this.origem != null) {
                    this.origem.preencherCliente(c);
                }
                this.dispose();
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente na tabela.");
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void tblBuscarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarClientesMouseClicked

    }//GEN-LAST:event_tblBuscarClientesMouseClicked

    private void txtPesquisarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarClienteKeyPressed
    String buscar = txtPesquisarCliente.getText();

        DefaultTableModel model = (DefaultTableModel) tblBuscarClientes.getModel();
        model.setNumRows(0);

        // 4. Preenche a tabela com a lista resultante (filtrada ou completa)
        for (Cliente c : cDAO.buscar(buscar)){
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getTelefone(),
            });
        }       
    }//GEN-LAST:event_txtPesquisarClienteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuscarClientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuscarClientes;
    private javax.swing.JTextField txtPesquisarCliente;
    // End of variables declaration//GEN-END:variables

private void atualizarTabela(String busca) {
        DefaultTableModel model = (DefaultTableModel) tblBuscarClientes.getModel();
        model.setNumRows(0); 

        List<Cliente> clientes = cc.filtrarClientes(busca);
        
       
        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getTelefone()
            });
        }
}

}


