/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luizfrancisco.estacionamento.view;

import com.luizfrancisco.estacionamento.controller.ClienteController;
import com.luizfrancisco.estacionamento.controller.OperacaoController;
import com.luizfrancisco.estacionamento.controller.VagaController;
import com.luizfrancisco.estacionamento.controller.VeiculoController;
import com.luizfrancisco.estacionamento.dao.ClienteDAO;
import com.luizfrancisco.estacionamento.dao.OperacaoDAO;
import com.luizfrancisco.estacionamento.dao.VagaDAO;
import com.luizfrancisco.estacionamento.dao.VeiculoDAO;
import com.luizfrancisco.estacionamento.model.Cliente;
import com.luizfrancisco.estacionamento.model.Operacao;
import com.luizfrancisco.estacionamento.model.Veiculo;
import com.luizfrancisco.estacionamento.model.Vaga;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {
    private static final VeiculoDAO vDAO = new VeiculoDAO();
    private static final ClienteDAO cDAO = new ClienteDAO();
    private static final OperacaoDAO oDAO = new OperacaoDAO();
    private static final VagaDAO vgDAO = new VagaDAO();
    private Cliente clienteSelecionado = null;
    private Veiculo veiculoSelecionado = null;
    private Vaga vagaSelecionada = null;
    private final ClienteController cc = new ClienteController();
    private int linhaSelecionada = -1;
    private final VeiculoController vc = new VeiculoController();
    private final VagaController vgc = new VagaController();
    private final OperacaoController oc = new OperacaoController();

    
    private int linha = -1;
    
    public Principal() {
        initComponents();
        cc.atualizaTabela(tblClientesPrincipal);
        vc.atualizaTabela(tblCadastroVeiculos);
        vgc.atualizaTabela(tblVagas);
        oc.atualizaTabela(operacaoTable);
        preencheCbxVaga();
        
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Principal = new javax.swing.JTabbedPane();
        Clientes = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNomeClienteCadastro = new javax.swing.JTextField();
        txtEmailClienteCadastro = new javax.swing.JTextField();
        txtTelefoneClienteCadastro = new javax.swing.JTextField();
        btnSalvarCadastroCliente = new javax.swing.JButton();
        btnSalvarCadastroCliente1 = new javax.swing.JButton();
        btnSalvarCadastroCliente5 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClientesPrincipal = new javax.swing.JTable();
        Veiculo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtPlacaVeiculoCadastro = new javax.swing.JTextField();
        txtCorVeiculoCadastro = new javax.swing.JTextField();
        txtModeloVeiculoCadastro = new javax.swing.JTextField();
        btnSalvarCadastroVeiculo = new javax.swing.JButton();
        btnDeletarVeiculo = new javax.swing.JButton();
        btnEditarVeiculo = new javax.swing.JButton();
        txtNomeClienteVeiculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCadastroVeiculos = new javax.swing.JTable();
        Operacional = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtPlacaOp = new javax.swing.JTextField();
        txtCorOp = new javax.swing.JTextField();
        txtModeloOp = new javax.swing.JTextField();
        btnSalvarCadastroCliente9 = new javax.swing.JButton();
        btnSalvarCadastroCliente10 = new javax.swing.JButton();
        btnSalvarCadastroCliente11 = new javax.swing.JButton();
        lblBuscarVeiculo = new javax.swing.JLabel();
        txtNomeClienteOp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFinalizarOp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarOperacao = new javax.swing.JTextField();
        btnBuscarOp = new javax.swing.JButton();
        cbxVagas = new javax.swing.JComboBox<>();
        ftdPrecoHora = new javax.swing.JFormattedTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        operacaoTable = new javax.swing.JTable();
        Vagas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVagas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de cliente"));

        txtNomeClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome completo do cliente"));

        txtEmailClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txtTelefoneClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        btnSalvarCadastroCliente.setText("Salvar");
        btnSalvarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroClienteActionPerformed(evt);
            }
        });

        btnSalvarCadastroCliente1.setText("Deletar");
        btnSalvarCadastroCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroCliente1ActionPerformed(evt);
            }
        });

        btnSalvarCadastroCliente5.setText("Editar");
        btnSalvarCadastroCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroCliente5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtNomeClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtTelefoneClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnSalvarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarCadastroCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarCadastroCliente5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 162, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroCliente)
                    .addComponent(btnSalvarCadastroCliente1)
                    .addComponent(btnSalvarCadastroCliente5))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        tblClientesPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome completo", "Email", "Telefone"
            }
        ));
        tblClientesPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesPrincipalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblClientesPrincipal);

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        Principal.addTab("Clientes", Clientes);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de veículo"));

        txtPlacaVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa"));

        txtCorVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor"));
        txtCorVeiculoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorVeiculoCadastroActionPerformed(evt);
            }
        });

        txtModeloVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        btnSalvarCadastroVeiculo.setText("Salvar");
        btnSalvarCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroVeiculoActionPerformed(evt);
            }
        });

        btnDeletarVeiculo.setText("Deletar");
        btnDeletarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarVeiculoActionPerformed(evt);
            }
        });

        btnEditarVeiculo.setText("Editar");

        txtNomeClienteVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        txtNomeClienteVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteVeiculoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Buscar cliente");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtPlacaVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtModeloVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtNomeClienteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnSalvarCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroVeiculo)
                    .addComponent(btnDeletarVeiculo)
                    .addComponent(btnEditarVeiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCadastroVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Modelo", "Cor", "Nome Cliente"
            }
        ));
        tblCadastroVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroVeiculosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCadastroVeiculos);
        if (tblCadastroVeiculos.getColumnModel().getColumnCount() > 0) {
            tblCadastroVeiculos.getColumnModel().getColumn(0).setResizable(false);
            tblCadastroVeiculos.getColumnModel().getColumn(1).setResizable(false);
            tblCadastroVeiculos.getColumnModel().getColumn(2).setResizable(false);
            tblCadastroVeiculos.getColumnModel().getColumn(3).setResizable(false);
            tblCadastroVeiculos.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout VeiculoLayout = new javax.swing.GroupLayout(Veiculo);
        Veiculo.setLayout(VeiculoLayout);
        VeiculoLayout.setHorizontalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VeiculoLayout.setVerticalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 124, Short.MAX_VALUE))
        );

        Principal.addTab("Veiculo", Veiculo);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar operacao"));

        txtPlacaOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa"));
        txtPlacaOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaOpActionPerformed(evt);
            }
        });

        txtCorOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor"));
        txtCorOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorOpActionPerformed(evt);
            }
        });

        txtModeloOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        btnSalvarCadastroCliente9.setText("Salvar");
        btnSalvarCadastroCliente9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroCliente9ActionPerformed(evt);
            }
        });

        btnSalvarCadastroCliente10.setText("Deletar");

        btnSalvarCadastroCliente11.setText("Editar");

        lblBuscarVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblBuscarVeiculo.setForeground(new java.awt.Color(0, 51, 204));
        lblBuscarVeiculo.setText("Buscar Veículo");
        lblBuscarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarVeiculoMouseClicked(evt);
            }
        });

        txtNomeClienteOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        txtNomeClienteOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteOpActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da operação"));

        jLabel1.setText("Horário entrada");

        jLabel2.setText("Horário saída");

        jLabel3.setText("Valor total");

        btnFinalizarOp.setBackground(new java.awt.Color(204, 204, 204));
        btnFinalizarOp.setText("Finalizar");
        btnFinalizarOp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnFinalizarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarOpActionPerformed(evt);
            }
        });

        jLabel4.setText("Código ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizarOp)
                .addContainerGap())
        );

        txtBuscarOperacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Operacao"));
        txtBuscarOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarOperacaoActionPerformed(evt);
            }
        });

        btnBuscarOp.setText("Buscar");

        cbxVagas.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a vaga"));
        cbxVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVagasActionPerformed(evt);
            }
        });

        ftdPrecoHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Preço/Hora"));
        ftdPrecoHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤¤#,##0.00"))));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtBuscarOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(btnSalvarCadastroCliente9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalvarCadastroCliente10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalvarCadastroCliente11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(196, 196, 196)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeClienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(cbxVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ftdPrecoHora, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblBuscarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtPlacaOp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtModeloOp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorOp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(txtNomeClienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxVagas)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftdPrecoHora)
                        .addComponent(lblBuscarVeiculo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarCadastroCliente9)
                            .addComponent(btnSalvarCadastroCliente10)
                            .addComponent(btnSalvarCadastroCliente11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarOp)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        operacaoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Vaga", "Placa Veiculo", "Entrada", "Saida", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(operacaoTable);
        if (operacaoTable.getColumnModel().getColumnCount() > 0) {
            operacaoTable.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout OperacionalLayout = new javax.swing.GroupLayout(Operacional);
        Operacional.setLayout(OperacionalLayout);
        OperacionalLayout.setHorizontalGroup(
            OperacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OperacionalLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OperacionalLayout.setVerticalGroup(
            OperacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionalLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Principal.addTab("Operacional", Operacional);

        tblVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID vaga", "Status", "Placa Veículo", "Modelo", "Marca"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVagas);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Buscar vaga");

        jButton5.setText("Limpar");

        jButton6.setText("Editar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações do cliente"));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nome:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Telefone:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Email:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da vaga"));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade de operações:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Valor total:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tempo total ocupada:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Código da vaga:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(14, 14, 14))
        );

        jButton7.setText("Liberar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(150, 150, 150))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VagasLayout = new javax.swing.GroupLayout(Vagas);
        Vagas.setLayout(VagasLayout);
        VagasLayout.setHorizontalGroup(
            VagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VagasLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        VagasLayout.setVerticalGroup(
            VagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VagasLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        Principal.addTab("Vagas", Vagas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnSalvarCadastroCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroCliente1ActionPerformed
// A variável 'linha' é definida pelo evento tblClientesPrincipalMouseClicked, 
    // mas é mais seguro pegar diretamente de tblClientesPrincipal.
    linha = tblClientesPrincipal.getSelectedRow(); 

    // 1. Verifica se alguma linha foi selecionada (linha < 0 significa que nada foi clicado)
    if (linha < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Nenhum cliente selecionado. Por favor, selecione um cliente na tabela.",
            "AVISO",
            JOptionPane.WARNING_MESSAGE
        );

    } else {
        // 2. Obtém o ID do cliente da coluna 0 da linha selecionada
        int idCliente = (int) tblClientesPrincipal.getValueAt(linha, 0);

        // 3. Pede confirmação antes de deletar
        int confirmacao = JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja excluir o cliente ID: " + idCliente + "?", 
                "Confirmação de Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // 4. Chama o DAO para deletar
                cDAO.deletar(idCliente);

                // 5. Atualiza a tabela para refletir a exclusão
                cc.atualizaTabela(tblClientesPrincipal);

                // 6. Limpa os campos de texto do cadastro de cliente
                limparCamposCliente(); // Você deve criar este método (veja abaixo)
                
                JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } catch (RuntimeException e) {
                // Trata a exceção de Foreign Key (se houver veículos vinculados)
                JOptionPane.showMessageDialog(this, 
                        "Erro ao excluir. O cliente possui veículos vinculados e não pode ser deletado.", 
                        "Erro de Exclusão", JOptionPane.ERROR_MESSAGE);
            }
        }
    }        
    }//GEN-LAST:event_btnSalvarCadastroCliente1ActionPerformed

    private void btnSalvarCadastroCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroCliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarCadastroCliente5ActionPerformed

    private void txtCorVeiculoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorVeiculoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorVeiculoCadastroActionPerformed

    private void txtNomeClienteVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteVeiculoActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new BuscarClientes(this).setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void txtCorOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorOpActionPerformed

    private void lblBuscarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarVeiculoMouseClicked
       new BuscarVeiculo(this).setVisible(true);
    }//GEN-LAST:event_lblBuscarVeiculoMouseClicked

    private void txtPlacaOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaOpActionPerformed

    private void txtNomeClienteOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteOpActionPerformed

    private void btnFinalizarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinalizarOpActionPerformed

    private void txtBuscarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarOperacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarOperacaoActionPerformed

    private void btnSalvarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroClienteActionPerformed
        Cliente c = retornaCliente();
    
    if(c != null){
        cDAO.inserir(c);
        
        // **********************************************
        // 1. CHAMA O CONTROLLER PARA ATUALIZAR A TABELA
        cc.atualizaTabela(tblClientesPrincipal);
        
        // 2. LIMPA OS CAMPOS APÓS A INSERÇÃO
        limparCamposCliente();
        // **********************************************
        
        JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
    }
    }//GEN-LAST:event_btnSalvarCadastroClienteActionPerformed

    private void btnSalvarCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroVeiculoActionPerformed
Veiculo v = retornaVeiculo();
    
    if(v != null){
        vDAO.inserir(v);
        
        // **********************************************
        // 1. CHAMA O CONTROLLER PARA ATUALIZAR A TABELA DE VEÍCULOS
        vc.atualizaTabela(tblCadastroVeiculos); // Use o nome correto da sua JTable de veículos
        
        // 2. LIMPA OS CAMPOS APÓS A INSERÇÃO
        limparCamposVeiculo(); 
        // **********************************************
        
        JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
    }
    }//GEN-LAST:event_btnSalvarCadastroVeiculoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void tblCadastroVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroVeiculosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCadastroVeiculosMouseClicked

    private void tblClientesPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesPrincipalMouseClicked
// 1. Armazena o índice da linha que foi clicada
    linha = tblClientesPrincipal.getSelectedRow();

    // 2. Verifica se uma linha válida foi selecionada
    if (linha > -1) {
        // 3. Obtém os valores da linha selecionada
        int id = (int) tblClientesPrincipal.getValueAt(linha, 0);
        String nome = tblClientesPrincipal.getValueAt(linha, 1).toString();
        
        // Cuidado! O valor da coluna 2 é o Email, não o Telefone.
        String email = tblClientesPrincipal.getValueAt(linha, 2) != null ? tblClientesPrincipal.getValueAt(linha, 2).toString() : ""; 
        String telefone = tblClientesPrincipal.getValueAt(linha, 3) != null ? tblClientesPrincipal.getValueAt(linha, 3).toString() : "";

        // 4. Cria um objeto Cliente e o armazena na variável de instância (se for usar para edição/exclusão)
        // Você pode não precisar desta linha se apenas for preencher os campos.
        // Cliente c = new Cliente(id, nome, email, telefone); 
        
        // 5. Preenche os campos de texto na aba de Cadastro de Cliente
        txtNomeClienteCadastro.setText(nome);
        txtEmailClienteCadastro.setText(email);
        
        // Corrigindo: No seu método retornaCliente, você usou 'txtEmailClienteCadastro' duas vezes.
        // O campo para telefone deve ser 'txtTelefoneClienteCadastro'.
        txtTelefoneClienteCadastro.setText(telefone); 
        }
    }//GEN-LAST:event_tblClientesPrincipalMouseClicked

    private void btnDeletarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarVeiculoActionPerformed
// Usando 'linhaVeiculo' como exemplo da variável que armazena a seleção
    int linhaVeiculo = tblCadastroVeiculos.getSelectedRow(); 

    if (linhaVeiculo < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Nenhum veículo selecionado, por favor selecione na tabela",
            "AVISO",
            JOptionPane.WARNING_MESSAGE
        );

    } else {
        // 1. Obtém o ID do veículo da coluna 0 (onde o ID deve estar)
        int idVeiculo = (int) tblCadastroVeiculos.getValueAt(linhaVeiculo, 0);

        int confirmacao = JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja excluir o veículo ID: " + idVeiculo + "?", 
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // 2. Chama o DAO para deletar
                vDAO.deletar(idVeiculo);
                
                // 3. ATUALIZA A TABELA e limpa os campos após o sucesso
                vc.atualizaTabela(tblCadastroVeiculos); 
                limparCamposVeiculo();

                JOptionPane.showMessageDialog(this, "Veículo excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } catch (RuntimeException e) {
                // Trata a exceção lançada pelo DAO (geralmente por Foreign Key)
                JOptionPane.showMessageDialog(this, 
                        "Erro ao excluir. O veículo pode estar em uso.", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }      
    }//GEN-LAST:event_btnDeletarVeiculoActionPerformed

    private void btnSalvarCadastroCliente9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroCliente9ActionPerformed
        if(veiculoSelecionado == null || vagaSelecionada == null){
            JOptionPane.showMessageDialog(this, "Selecione um veículo e uma vaga!");
            return;
        }
        try{
            String precoTexto = ftdPrecoHora.getText();
            double preco = Double.parseDouble(precoTexto);
            Operacao op = retornaOperacao(veiculoSelecionado, vagaSelecionada, preco);
            oDAO.inserirEntrada(op);
            JOptionPane.showMessageDialog(this, "Entrada registrada com sucesso!");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarCadastroCliente9ActionPerformed

    private void cbxVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVagasActionPerformed
        
    }//GEN-LAST:event_cbxVagasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Operacional;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JPanel Vagas;
    private javax.swing.JPanel Veiculo;
    private javax.swing.JButton btnBuscarOp;
    private javax.swing.JButton btnDeletarVeiculo;
    private javax.swing.JButton btnEditarVeiculo;
    private javax.swing.JButton btnFinalizarOp;
    private javax.swing.JButton btnSalvarCadastroCliente;
    private javax.swing.JButton btnSalvarCadastroCliente1;
    private javax.swing.JButton btnSalvarCadastroCliente10;
    private javax.swing.JButton btnSalvarCadastroCliente11;
    private javax.swing.JButton btnSalvarCadastroCliente5;
    private javax.swing.JButton btnSalvarCadastroCliente9;
    private javax.swing.JButton btnSalvarCadastroVeiculo;
    private javax.swing.JComboBox<Vaga> cbxVagas;
    private javax.swing.JFormattedTextField ftdPrecoHora;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblBuscarVeiculo;
    private javax.swing.JTable operacaoTable;
    private javax.swing.JTable tblCadastroVeiculos;
    private javax.swing.JTable tblClientesPrincipal;
    private javax.swing.JTable tblVagas;
    private javax.swing.JTextField txtBuscarOperacao;
    private javax.swing.JTextField txtCorOp;
    private javax.swing.JTextField txtCorVeiculoCadastro;
    private javax.swing.JTextField txtEmailClienteCadastro;
    private javax.swing.JTextField txtModeloOp;
    private javax.swing.JTextField txtModeloVeiculoCadastro;
    private javax.swing.JTextField txtNomeClienteCadastro;
    private javax.swing.JTextField txtNomeClienteOp;
    private javax.swing.JTextField txtNomeClienteVeiculo;
    private javax.swing.JTextField txtPlacaOp;
    private javax.swing.JTextField txtPlacaVeiculoCadastro;
    private javax.swing.JTextField txtTelefoneClienteCadastro;
    // End of variables declaration//GEN-END:variables
private Cliente retornaCliente(){
        String nome = txtNomeClienteCadastro.getText();
        String email = txtEmailClienteCadastro.getText();
        String telefone = txtTelefoneClienteCadastro.getText();
        
        Cliente c = new Cliente();
        c.setNome(nome);
        c.setEmail(email);
        c.setTelefone(telefone);
        return c;
    }

private Veiculo retornaVeiculo(){
        String placa = txtPlacaVeiculoCadastro.getText();
        String modelo = txtModeloVeiculoCadastro.getText();
        String cor = txtCorVeiculoCadastro.getText();
        
        if(this.clienteSelecionado == null){
            JOptionPane.showMessageDialog(this, "Não foi selecionado nenhum cliente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
        Veiculo v = new Veiculo();
        v.setCor(cor);
        v.setModelo(modelo);
        v.setPlaca(placa);
        
        v.setCliente(this.clienteSelecionado);
        return v;
    }

private Operacao retornaOperacao(Veiculo veiculo, Vaga vaga, double precoHora){

    Operacao op = new Operacao();
    op.setHorarioEntrada(LocalDateTime.now());
    op.setVeiculo(veiculo);
    op.setVaga(vaga);
    op.setValorHora(precoHora);
    
    op.setValorTotal(0.0);
    
    return op;
}

public void preencherCliente(Cliente c){
        this.clienteSelecionado = c;
        txtNomeClienteVeiculo.setText(c.getNome());
    }
public void preencherVeiculo(Veiculo v){
        this.veiculoSelecionado = v;
        txtPlacaOp.setText(v.getPlaca());
        txtModeloOp.setText(v.getModelo());
        txtCorOp.setText(v.getCor());
        txtNomeClienteOp.setText(v.getCliente().getNome());
    }
public void limparCamposCliente() {
    txtNomeClienteCadastro.setText("");
    txtEmailClienteCadastro.setText("");
    txtTelefoneClienteCadastro.setText("");

    linha = -1;
    }
public void limparCamposVeiculo() {
    // Limpa os campos de texto na aba de Cadastro de Veículo
    txtPlacaVeiculoCadastro.setText("");
    txtModeloVeiculoCadastro.setText("");
    txtCorVeiculoCadastro.setText("");
    txtNomeClienteVeiculo.setText(""); 

    this.clienteSelecionado = null; 

    }

public void preencheCbxVaga(){
    cbxVagas.removeAllItems();

    
    for (Vaga v : vgDAO.listarVagas())
        cbxVagas.addItem(v);
    }
}
