/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luizfrancisco.estacionamento.view;

import com.luizfrancisco.estacionamento.controller.ClienteController;
import com.luizfrancisco.estacionamento.controller.OperacaoController;
import com.luizfrancisco.estacionamento.controller.VagaController;
import com.luizfrancisco.estacionamento.controller.VeiculoController;
import com.luizfrancisco.estacionamento.database.Conexao;
import com.luizfrancisco.estacionamento.model.Cliente;
import com.luizfrancisco.estacionamento.model.Veiculo;
import com.luizfrancisco.estacionamento.model.Vaga;
import java.util.List;
import java.time.LocalDateTime;
import com.luizfrancisco.estacionamento.model.Operacao;
import com.luizfrancisco.estacionamento.util.RelatorioUtil;
import java.sql.Connection;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.luizfrancisco.estacionamento.model.EstatisticaVaga;
import com.luizfrancisco.estacionamento.model.Usuario;
import com.luizfrancisco.estacionamento.util.ValidadorDeCampos;
import java.awt.Color;

/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {
    private Cliente clienteSelecionado = null;
    private Veiculo veiculoSelecionado = null;
    private Operacao op;
    private final ClienteController cc = new ClienteController();
    private int linhaSelecionada = -1;
    private final VeiculoController vc = new VeiculoController();
    private final VagaController vgc = new VagaController();
    private final OperacaoController oc = new OperacaoController();
    
    private Usuario usuarioLogado;
    
    
    public Principal() {
        initComponents();
        iniciarConfiguracoes();
        setLocationRelativeTo(this);
        setResizable(false); 
    }
    
    public Principal(Usuario usuario) {
        initComponents(); 
        
        this.usuarioLogado = usuario; 
        
        iniciarConfiguracoes(); 
        
        this.setResizable(false);
        verificarPermissoes(); 
    }
    
    private void iniciarConfiguracoes() {
        txtValorHora.setText("R$ 0,00");
        atualizarTabelaClientes("");
        atualizarTabelaVeiculos("");
        atualizarTabelaVagas("");
        atualizarTabelaOperacoes("");
        configurarListeners();
        preencheCbxVaga();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) { 
             new Login().setVisible(true);;
        }
    });
    }
    
    private void verificarPermissoes() {
        
        
        
        if (this.usuarioLogado != null && this.usuarioLogado.getRole().equalsIgnoreCase("colaborador")) {
            btnDeletarVeiculo.setEnabled(false);
            btnDeletarCliente.setEnabled(false);
            btnDeletarOp.setEnabled(false);
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vagasBtnGroup = new javax.swing.ButtonGroup();
        Principal = new javax.swing.JTabbedPane();
        Clientes = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtNomeClienteCadastro = new javax.swing.JTextField();
        txtEmailClienteCadastro = new javax.swing.JTextField();
        txtTelefoneClienteCadastro = new javax.swing.JTextField();
        btnSalvarCadastroCliente = new javax.swing.JButton();
        btnDeletarCliente = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        btnLimparCliente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClientesPrincipal = new javax.swing.JTable();
        Veiculo = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        txtPlacaVeiculoCadastro = new javax.swing.JTextField();
        txtCorVeiculoCadastro = new javax.swing.JTextField();
        txtModeloVeiculoCadastro = new javax.swing.JTextField();
        btnSalvarCadastroVeiculo = new javax.swing.JButton();
        btnDeletarVeiculo = new javax.swing.JButton();
        txtNomeClienteVeiculo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtBuscarVeiculo = new javax.swing.JTextField();
        btnBuscarVeiculo = new javax.swing.JButton();
        btnLimparVeiculo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCadastroVeiculos = new javax.swing.JTable();
        Operacional = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txtPlacaOp = new javax.swing.JTextField();
        txtCorOp = new javax.swing.JTextField();
        txtModeloOp = new javax.swing.JTextField();
        btnSalvarCadastroOperacao = new javax.swing.JButton();
        btnDeletarOp = new javax.swing.JButton();
        lblBuscarVeiculo = new javax.swing.JLabel();
        txtNomeClienteOp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFinalizarOp = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblDadosCodigo = new javax.swing.JLabel();
        lblDadosEntrada = new javax.swing.JLabel();
        lblDadosSaida = new javax.swing.JLabel();
        lblDadosValorTotal = new javax.swing.JLabel();
        lvl = new javax.swing.JLabel();
        lblDadosCodigoOp = new javax.swing.JLabel();
        txtBuscarOperacao = new javax.swing.JTextField();
        btnBuscarOp = new javax.swing.JButton();
        cbxVagas = new javax.swing.JComboBox<>();
        btnImprimirRelatorio = new javax.swing.JToggleButton();
        txtValorHora = new javax.swing.JTextField();
        btnLimparOp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblOperacao = new javax.swing.JTable();
        Vagas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVagas = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtBuscarVaga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarVaga = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblVaga4 = new javax.swing.JLabel();
        lblvaga1 = new javax.swing.JLabel();
        lblVaga3 = new javax.swing.JLabel();
        lblVaga2 = new javax.swing.JLabel();
        lblCodVagaInfo = new javax.swing.JLabel();
        lblQtdOpVagaInfo = new javax.swing.JLabel();
        lblValTotalVagaInfo = new javax.swing.JLabel();
        lblTempoTotalVagaInfo = new javax.swing.JLabel();
        rdbLivre = new javax.swing.JRadioButton();
        rdbOcupada = new javax.swing.JRadioButton();
        rdbTodas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Principal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de cliente"));

        txtNomeClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome completo do cliente"));

        txtEmailClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Email"));

        txtTelefoneClienteCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        btnSalvarCadastroCliente.setText("Salvar");
        btnSalvarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroClienteActionPerformed(evt);
            }
        });

        btnDeletarCliente.setText("Deletar");
        btnDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarClienteActionPerformed(evt);
            }
        });

        txtBuscarCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Cliente"));
        txtBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarClienteActionPerformed(evt);
            }
        });
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyPressed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnLimparCliente.setText("Limpar");
        btnLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtNomeClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtTelefoneClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmailClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnSalvarCadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnLimparCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 162, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailClienteCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastroCliente)
                    .addComponent(btnDeletarCliente)
                    .addComponent(btnLimparCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)))
        );

        tblClientesPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome completo", "Email", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientesPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesPrincipalMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblClientesPrincipal);

        javax.swing.GroupLayout ClientesLayout = new javax.swing.GroupLayout(Clientes);
        Clientes.setLayout(ClientesLayout);
        ClientesLayout.setHorizontalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        ClientesLayout.setVerticalGroup(
            ClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClientesLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );

        Principal.addTab("Clientes", Clientes);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de veículo"));

        txtPlacaVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa"));

        txtCorVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor"));
        txtCorVeiculoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorVeiculoCadastroActionPerformed(evt);
            }
        });

        txtModeloVeiculoCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        btnSalvarCadastroVeiculo.setText("Salvar");
        btnSalvarCadastroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroVeiculoActionPerformed(evt);
            }
        });

        btnDeletarVeiculo.setText("Deletar");
        btnDeletarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarVeiculoActionPerformed(evt);
            }
        });

        txtNomeClienteVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        txtNomeClienteVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteVeiculoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Buscar cliente");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        txtBuscarVeiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Veiculo"));
        txtBuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVeiculoActionPerformed(evt);
            }
        });
        txtBuscarVeiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarVeiculoKeyPressed(evt);
            }
        });

        btnBuscarVeiculo.setText("Buscar");
        btnBuscarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVeiculoActionPerformed(evt);
            }
        });

        btnLimparVeiculo.setText("Limpar");
        btnLimparVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparVeiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(txtNomeClienteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(txtPlacaVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtModeloVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(btnSalvarCadastroVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(btnLimparVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(txtBuscarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCorVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorVeiculoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeClienteVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVeiculo))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarCadastroVeiculo)
                        .addComponent(btnDeletarVeiculo)
                        .addComponent(btnLimparVeiculo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblCadastroVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Modelo", "Cor", "Nome Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCadastroVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadastroVeiculosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCadastroVeiculos);

        javax.swing.GroupLayout VeiculoLayout = new javax.swing.GroupLayout(Veiculo);
        Veiculo.setLayout(VeiculoLayout);
        VeiculoLayout.setHorizontalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VeiculoLayout.setVerticalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
        );

        Principal.addTab("Veiculo", Veiculo);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar operacao"));

        txtPlacaOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Placa"));
        txtPlacaOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaOpActionPerformed(evt);
            }
        });

        txtCorOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor"));
        txtCorOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorOpActionPerformed(evt);
            }
        });

        txtModeloOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Modelo"));

        btnSalvarCadastroOperacao.setText("Salvar");
        btnSalvarCadastroOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroOperacaoActionPerformed(evt);
            }
        });

        btnDeletarOp.setText("Deletar");
        btnDeletarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarOpActionPerformed(evt);
            }
        });

        lblBuscarVeiculo.setFont(new java.awt.Font("Fira Sans", 1, 14)); // NOI18N
        lblBuscarVeiculo.setForeground(new java.awt.Color(0, 51, 204));
        lblBuscarVeiculo.setText("Buscar Veículo");
        lblBuscarVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuscarVeiculoMouseClicked(evt);
            }
        });

        txtNomeClienteOp.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));
        txtNomeClienteOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteOpActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da operação"));

        jLabel1.setText("Entrada:");

        jLabel2.setText("Saída:");

        jLabel3.setText("Valor total:");

        btnFinalizarOp.setBackground(new java.awt.Color(255, 255, 241));
        btnFinalizarOp.setText("Finalizar");
        btnFinalizarOp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnFinalizarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarOpActionPerformed(evt);
            }
        });

        jLabel4.setText("Código vaga: ");

        lblDadosCodigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDadosEntrada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDadosSaida.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblDadosValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lvl.setText("Código Operação:");

        lblDadosCodigoOp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFinalizarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDadosCodigo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDadosEntrada))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lvl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDadosCodigoOp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDadosSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDadosValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblDadosCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvl)
                    .addComponent(lblDadosCodigoOp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDadosEntrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDadosSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblDadosValorTotal))
                .addGap(18, 18, 18)
                .addComponent(btnFinalizarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBuscarOperacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Operacao"));
        txtBuscarOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarOperacaoActionPerformed(evt);
            }
        });
        txtBuscarOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarOperacaoKeyPressed(evt);
            }
        });

        btnBuscarOp.setText("Buscar");
        btnBuscarOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarOpActionPerformed(evt);
            }
        });

        cbxVagas.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione a vaga"));
        cbxVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxVagasActionPerformed(evt);
            }
        });

        btnImprimirRelatorio.setBackground(new java.awt.Color(255, 255, 250));
        btnImprimirRelatorio.setText("Imprimir relatório");
        btnImprimirRelatorio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnImprimirRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirRelatorioActionPerformed(evt);
            }
        });

        txtValorHora.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor/Hora"));

        btnLimparOp.setText("Limpar");
        btnLimparOp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparOpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtBuscarOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImprimirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(txtPlacaOp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModeloOp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(cbxVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblBuscarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(btnSalvarCadastroOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDeletarOp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimparOp, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(txtCorOp, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txtNomeClienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlacaOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(txtNomeClienteOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxVagas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtValorHora)
                                .addComponent(lblBuscarVeiculo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSalvarCadastroOperacao)
                            .addComponent(btnDeletarOp)
                            .addComponent(btnLimparOp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarOp)
                            .addComponent(btnImprimirRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tblOperacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Vaga", "Placa Veiculo", "Entrada", "Saida", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOperacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOperacaoMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblOperacao);

        javax.swing.GroupLayout OperacionalLayout = new javax.swing.GroupLayout(Operacional);
        Operacional.setLayout(OperacionalLayout);
        OperacionalLayout.setHorizontalGroup(
            OperacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(OperacionalLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OperacionalLayout.setVerticalGroup(
            OperacionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OperacionalLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        Principal.addTab("Operacional", Operacional);

        tblVagas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID vaga", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVagas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVagasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblVagasMouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblVagas);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        txtBuscarVaga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarVagaKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Buscar vaga");

        btnBuscarVaga.setText("Buscar");
        btnBuscarVaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVagaActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações da vaga"));

        lblVaga4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVaga4.setText("Quantidade de operações:");

        lblvaga1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblvaga1.setText("Valor total:");

        lblVaga3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVaga3.setText("Tempo total ocupada:");

        lblVaga2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVaga2.setText("Código da vaga:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblvaga1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblValTotalVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblVaga2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblVaga4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQtdOpVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblVaga3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempoTotalVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaga2)
                    .addComponent(lblCodVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblQtdOpVagaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblVaga4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblvaga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblValTotalVagaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVaga3)
                    .addComponent(lblTempoTotalVagaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        rdbLivre.setBackground(new java.awt.Color(255, 255, 255));
        vagasBtnGroup.add(rdbLivre);
        rdbLivre.setText("Livre");
        rdbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbLivreActionPerformed(evt);
            }
        });

        rdbOcupada.setBackground(new java.awt.Color(255, 255, 255));
        vagasBtnGroup.add(rdbOcupada);
        rdbOcupada.setText("Ocupada");
        rdbOcupada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbOcupadaActionPerformed(evt);
            }
        });

        rdbTodas.setBackground(new java.awt.Color(255, 255, 255));
        vagasBtnGroup.add(rdbTodas);
        rdbTodas.setText("Todas");
        rdbTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnBuscarVaga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdbTodas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbLivre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbOcupada))
                            .addComponent(txtBuscarVaga))
                        .addGap(66, 66, 66)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarVaga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarVaga)
                            .addComponent(rdbLivre)
                            .addComponent(rdbOcupada)
                            .addComponent(rdbTodas))))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VagasLayout = new javax.swing.GroupLayout(Vagas);
        Vagas.setLayout(VagasLayout);
        VagasLayout.setHorizontalGroup(
            VagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(VagasLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        VagasLayout.setVerticalGroup(
            VagasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VagasLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))
        );

        Principal.addTab("Vagas", Vagas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarClienteActionPerformed

    linhaSelecionada = tblClientesPrincipal.getSelectedRow(); 
    if (linhaSelecionada < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Nenhum cliente selecionado. Por favor, selecione um cliente na tabela.",
            "AVISO",
            JOptionPane.WARNING_MESSAGE
        );

    } else {
        int idCliente = (int) tblClientesPrincipal.getValueAt(linhaSelecionada, 0);
            try {              
                cc.deletarCliente(idCliente);              
                atualizarTabelaClientes("");
                limparCamposCliente();
                JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage(), "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
                

    }        
    }//GEN-LAST:event_btnDeletarClienteActionPerformed

    private void txtCorVeiculoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorVeiculoCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorVeiculoCadastroActionPerformed

    private void txtNomeClienteVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteVeiculoActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        new BuscarClientes(this).setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void txtCorOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorOpActionPerformed

    private void lblBuscarVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarVeiculoMouseClicked
       new BuscarVeiculo(this).setVisible(true);
    }//GEN-LAST:event_lblBuscarVeiculoMouseClicked

    private void txtPlacaOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaOpActionPerformed

    private void txtNomeClienteOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteOpActionPerformed

    private void btnFinalizarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarOpActionPerformed
        linhaSelecionada = tblOperacao.getSelectedRow();
        if(linhaSelecionada != -1 ){
           int id = (int) tblOperacao.getValueAt(linhaSelecionada, 0);
           this.op = oc.buscarOp(id);
           oc.checkout(id);
           atualizarEstadoBotaoFinalizar(id);
           atualizarPainelDadosOperacao(op);
           atualizarTabelaOperacoes("");
           preencheCbxVaga();
           JOptionPane.showMessageDialog(this, "Operação finalizada!");
        
               
               
           
        }
    }//GEN-LAST:event_btnFinalizarOpActionPerformed

    private void txtBuscarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarOperacaoActionPerformed

    }//GEN-LAST:event_txtBuscarOperacaoActionPerformed

    private void btnSalvarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroClienteActionPerformed

        if(ValidadorDeCampos.temCampoVazio(txtNomeClienteCadastro, "Nome do cliente")) return;
        if(ValidadorDeCampos.temCampoVazio(txtEmailClienteCadastro, "Email do cliente")) return;
        if(ValidadorDeCampos.temCampoVazio(txtTelefoneClienteCadastro, "Telefone do cliente")) return;
        if(ValidadorDeCampos.isEmailInvalido(txtEmailClienteCadastro)) return;
        Cliente c = retornaCliente();
        if (c != null) {
            try {
                if (linhaSelecionada > -1) {
            
                    int id = (int) tblClientesPrincipal.getValueAt(linhaSelecionada, 0);
                    cc.editarCliente(id, c);
                    JOptionPane.showMessageDialog(this, "Cliente atualizado com sucesso!");
                } else {
            
                    cc.cadastrarCliente(c);
                    JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
                }
        
       
                atualizarTabelaClientes("");
                limparCamposCliente();
        
         } catch (Exception e) { 
                e.printStackTrace(); 
                JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
    }
}
       
  
    }//GEN-LAST:event_btnSalvarCadastroClienteActionPerformed

    private void btnSalvarCadastroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroVeiculoActionPerformed
        if(ValidadorDeCampos.temCampoVazio(txtPlacaVeiculoCadastro, "Placa do veículo")) return;
        if(ValidadorDeCampos.temCampoVazio(txtModeloVeiculoCadastro, "Modelo do veículo")) return;
        if(ValidadorDeCampos.temCampoVazio(txtCorVeiculoCadastro, "Cor do veículo")) return;
        if(ValidadorDeCampos.temCampoVazio(txtNomeClienteVeiculo, "Cor do veículo")) return;
        
        
        Veiculo v = retornaVeiculo();
    
        if(v != null){
            try{
                if(linhaSelecionada > -1){
                    int id = (int) tblCadastroVeiculos.getValueAt(linhaSelecionada, 0);
                    vc.atualizarVeiculo(id, v);
                    System.out.println(id);
                    System.out.println(v.getCliente().getNome());
                    JOptionPane.showMessageDialog(this, "Veículo atualizado com sucesso!");
                }else {
                    vc.cadastrarVeiculo(v);
                    JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
                }
                atualizarTabelaVeiculos("");
                limparCamposVeiculo();
            
            }catch(Exception e){
                e.printStackTrace(); 
                JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_btnSalvarCadastroVeiculoActionPerformed

    private void tblCadastroVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadastroVeiculosMouseClicked
        linhaSelecionada = tblCadastroVeiculos.getSelectedRow();
        int idVeiculo = (int) tblCadastroVeiculos.getValueAt(linhaSelecionada, 0);
        
        
        
        try{
            String termoDeBusca = String.valueOf(idVeiculo);
            List<Veiculo> resultado = vc.filtrarVeiculos(termoDeBusca);
            
            for(Veiculo v : resultado){
            if(v.getId() == idVeiculo){
                txtPlacaVeiculoCadastro.setText(v.getPlaca());
                txtModeloVeiculoCadastro.setText(v.getModelo());
                txtCorVeiculoCadastro.setText(v.getCor());
                this.clienteSelecionado = v.getCliente();
                txtNomeClienteVeiculo.setText(v.getCliente().getNome());
                break;
            }
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, 
            "Erro ao carregar dados do veículo: " + e.getMessage(),
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        }
    }//GEN-LAST:event_tblCadastroVeiculosMouseClicked

    private void tblClientesPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesPrincipalMouseClicked

    linhaSelecionada = tblClientesPrincipal.getSelectedRow();

   
        if (linhaSelecionada > -1) {
        int id = (int) tblClientesPrincipal.getValueAt(linhaSelecionada, 0);
        String nome = tblClientesPrincipal.getValueAt(linhaSelecionada, 1) != null ? tblClientesPrincipal.getValueAt(linhaSelecionada, 1).toString() : "";
        String email = tblClientesPrincipal.getValueAt(linhaSelecionada, 2) != null ? tblClientesPrincipal.getValueAt(linhaSelecionada, 2).toString() : ""; 
        String telefone = tblClientesPrincipal.getValueAt(linhaSelecionada, 3) != null ? tblClientesPrincipal.getValueAt(linhaSelecionada, 3).toString() : "";
        txtNomeClienteCadastro.setText(nome);
        txtEmailClienteCadastro.setText(email);

        txtTelefoneClienteCadastro.setText(telefone); 
        }
    }//GEN-LAST:event_tblClientesPrincipalMouseClicked

    private void btnDeletarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarVeiculoActionPerformed

    int linhaVeiculo = tblCadastroVeiculos.getSelectedRow(); 

    if (linhaVeiculo < 0) {
        JOptionPane.showMessageDialog(
            this,
            "Nenhum veículo selecionado, por favor selecione na tabela",
            "AVISO",
            JOptionPane.WARNING_MESSAGE
        );

    } else {
       
        int idVeiculo = (int) tblCadastroVeiculos.getValueAt(linhaVeiculo, 0);

        int confirmacao = JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja excluir o veículo ID: " + idVeiculo + "?", 
                "Confirmação", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {

                vc.deletarVeiculo(idVeiculo);
                

                atualizarTabelaVeiculos("");
                limparCamposVeiculo();

                JOptionPane.showMessageDialog(this, "Veículo excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            } catch (RuntimeException e) {
           
                JOptionPane.showMessageDialog(this, 
                        "Erro ao excluir. O veículo pode estar em uso.", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }      
    }//GEN-LAST:event_btnDeletarVeiculoActionPerformed

    private void btnSalvarCadastroOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroOperacaoActionPerformed
        Operacao op = retornaOperacao();
        Vaga vagaDoCombo = (Vaga) cbxVagas.getSelectedItem(); 
        if(op != null){
            try{
                op.setVaga(vagaDoCombo);
                if(linhaSelecionada > -1){
                
                    if (this.op != null && this.op.getHorarioSaida() != null) {
                        JOptionPane.showMessageDialog(this, 
                        "Esta operação já foi finalizada. \nNão é permitido alterá-la.", 
                        "Bloqueado", 
                        JOptionPane.WARNING_MESSAGE);
                        return; 
                    }
                    int id = (int) tblOperacao.getValueAt(linhaSelecionada, 0);
                    oc.atualizarOperacao(id, op);
                    JOptionPane.showMessageDialog(this, "Operação atualizada com sucesso!");
                }else {
                    oc.registrarEntrada(op);
                    JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
                }
                atualizarTabelaOperacoes("");
                limparCamposOperacao();
                preencheCbxVaga();
                
            
            }catch(Exception e){
                e.printStackTrace(); 
                JOptionPane.showMessageDialog(this, "Erro ao salvar: " + e.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSalvarCadastroOperacaoActionPerformed

    private void cbxVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxVagasActionPerformed
        
    }//GEN-LAST:event_cbxVagasActionPerformed

    private void txtBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarClienteActionPerformed

    private void txtBuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVeiculoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
    atualizarTabelaOperacoes(txtBuscarOperacao.getText());
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtBuscarOperacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarOperacaoKeyPressed
    atualizarTabelaOperacoes(txtBuscarOperacao.getText());
    }//GEN-LAST:event_txtBuscarOperacaoKeyPressed

    private void txtBuscarVagaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVagaKeyPressed
    atualizarTabelaVagas(txtBuscarVaga.getText());
    }//GEN-LAST:event_txtBuscarVagaKeyPressed

    private void btnBuscarVagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVagaActionPerformed

    }//GEN-LAST:event_btnBuscarVagaActionPerformed

    private void txtBuscarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyPressed
    String buscar = txtBuscarCliente.getText();
        DefaultTableModel model = (DefaultTableModel) tblClientesPrincipal.getModel();
        model.setNumRows(0);

       
        for (Cliente c : cc.filtrarClientes(buscar)){
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getTelefone(),
            });
        }    
    }//GEN-LAST:event_txtBuscarClienteKeyPressed

    private void txtBuscarVeiculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarVeiculoKeyPressed
    atualizarTabelaVeiculos(txtBuscarVeiculo.getText());
    }//GEN-LAST:event_txtBuscarVeiculoKeyPressed

    private void btnBuscarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVeiculoActionPerformed
        String buscar = txtBuscarVeiculo.getText();
        atualizarTabelaVeiculos(buscar);
    }//GEN-LAST:event_btnBuscarVeiculoActionPerformed

    private void btnBuscarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarOpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarOpActionPerformed

    private void rdbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbLivreActionPerformed
            atualizarTabelaVagas(txtBuscarVaga.getText());
    }//GEN-LAST:event_rdbLivreActionPerformed

    private void rdbOcupadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbOcupadaActionPerformed
        atualizarTabelaVagas(txtBuscarVaga.getText());
    }//GEN-LAST:event_rdbOcupadaActionPerformed

    private void rdbTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTodasActionPerformed
            atualizarTabelaVagas(txtBuscarVaga.getText());
    }//GEN-LAST:event_rdbTodasActionPerformed

    private void tblOperacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOperacaoMouseClicked
        linhaSelecionada = tblOperacao.getSelectedRow();

        if (linhaSelecionada > -1) {
   
        int id = (int) tblOperacao.getValueAt(linhaSelecionada, 0);
        this.op = oc.buscarOp(id);
        
            if(this.op != null){
                atualizarPainelDadosOperacao(op);
                if(this.op.getVeiculo() != null){
                    preencherVeiculo(this.op.getVeiculo());
                }
                
                if(this.op.getVeiculo().getCliente() != null){
                    preencherCliente(this.op.getVeiculo().getCliente());
                }
                double valor = op.getValorHora();
                String valorFormatado = String.format("%.2f", valor);
                txtValorHora.setText(valorFormatado);
            }
        }

    }//GEN-LAST:event_tblOperacaoMouseClicked


    private void tblVagasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVagasMouseClicked
       linhaSelecionada = tblVagas.getSelectedRow();

       if(linhaSelecionada > -1){
           int id = (int) tblVagas.getValueAt(linhaSelecionada, 0);
           EstatisticaVaga ev = vgc.estatisticasVaga(id);

           lblCodVagaInfo.setText(String.valueOf(id));
           lblQtdOpVagaInfo.setText(String.valueOf(ev.getQtd()));
           lblValTotalVagaInfo.setText(String.format("R$ %.2f", ev.getValor()));
           lblTempoTotalVagaInfo.setText(ev.getTempoFormatado());
       }
    }//GEN-LAST:event_tblVagasMouseClicked

    private void tblVagasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVagasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVagasMouseEntered

    private void btnImprimirRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirRelatorioActionPerformed
        gerarRelatorio("relatorio_estacionamento");
    }//GEN-LAST:event_btnImprimirRelatorioActionPerformed

    private void btnDeletarOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarOpActionPerformed
       linhaSelecionada = tblOperacao.getSelectedRow();
       
       try{
           if(linhaSelecionada > -1){
           int id = (int) tblOperacao.getValueAt(linhaSelecionada, 0);
           this.op = oc.buscarOp(id);
            if(op.getHorarioSaida() == null){
                JOptionPane.showMessageDialog(this, 
                        "Operação ainda não foi finalizada!.", 
                        "Erro", JOptionPane.ERROR_MESSAGE);
            }else{
                oc.deletarOperacao(id);
                JOptionPane.showMessageDialog(this, "Operação excluida!");
                atualizarTabelaOperacoes("");
                preencheCbxVaga();
            }
          
           }
       }catch(Exception e){
           System.out.println("ERRO -> " + e);
       }
    }//GEN-LAST:event_btnDeletarOpActionPerformed

    private void btnLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparClienteActionPerformed
       limparCamposCliente();
    }//GEN-LAST:event_btnLimparClienteActionPerformed

    private void btnLimparVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparVeiculoActionPerformed
        limparCamposVeiculo();
    }//GEN-LAST:event_btnLimparVeiculoActionPerformed

    private void btnLimparOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparOpActionPerformed
        limparCamposOperacao();
    }//GEN-LAST:event_btnLimparOpActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Operacional;
    private javax.swing.JTabbedPane Principal;
    private javax.swing.JPanel Vagas;
    private javax.swing.JPanel Veiculo;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarOp;
    private javax.swing.JButton btnBuscarVaga;
    private javax.swing.JButton btnBuscarVeiculo;
    private javax.swing.JButton btnDeletarCliente;
    private javax.swing.JButton btnDeletarOp;
    private javax.swing.JButton btnDeletarVeiculo;
    private javax.swing.JButton btnFinalizarOp;
    private javax.swing.JToggleButton btnImprimirRelatorio;
    private javax.swing.JButton btnLimparCliente;
    private javax.swing.JButton btnLimparOp;
    private javax.swing.JButton btnLimparVeiculo;
    private javax.swing.JButton btnSalvarCadastroCliente;
    private javax.swing.JButton btnSalvarCadastroOperacao;
    private javax.swing.JButton btnSalvarCadastroVeiculo;
    private javax.swing.JComboBox<Vaga> cbxVagas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBuscarVeiculo;
    private javax.swing.JLabel lblCodVagaInfo;
    private javax.swing.JLabel lblDadosCodigo;
    private javax.swing.JLabel lblDadosCodigoOp;
    private javax.swing.JLabel lblDadosEntrada;
    private javax.swing.JLabel lblDadosSaida;
    private javax.swing.JLabel lblDadosValorTotal;
    private javax.swing.JLabel lblQtdOpVagaInfo;
    private javax.swing.JLabel lblTempoTotalVagaInfo;
    private javax.swing.JLabel lblVaga2;
    private javax.swing.JLabel lblVaga3;
    private javax.swing.JLabel lblVaga4;
    private javax.swing.JLabel lblValTotalVagaInfo;
    private javax.swing.JLabel lblvaga1;
    private javax.swing.JLabel lvl;
    private javax.swing.JRadioButton rdbLivre;
    private javax.swing.JRadioButton rdbOcupada;
    private javax.swing.JRadioButton rdbTodas;
    private javax.swing.JTable tblCadastroVeiculos;
    private javax.swing.JTable tblClientesPrincipal;
    private javax.swing.JTable tblOperacao;
    private javax.swing.JTable tblVagas;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarOperacao;
    private javax.swing.JTextField txtBuscarVaga;
    private javax.swing.JTextField txtBuscarVeiculo;
    private javax.swing.JTextField txtCorOp;
    private javax.swing.JTextField txtCorVeiculoCadastro;
    private javax.swing.JTextField txtEmailClienteCadastro;
    private javax.swing.JTextField txtModeloOp;
    private javax.swing.JTextField txtModeloVeiculoCadastro;
    private javax.swing.JTextField txtNomeClienteCadastro;
    private javax.swing.JTextField txtNomeClienteOp;
    private javax.swing.JTextField txtNomeClienteVeiculo;
    private javax.swing.JTextField txtPlacaOp;
    private javax.swing.JTextField txtPlacaVeiculoCadastro;
    private javax.swing.JTextField txtTelefoneClienteCadastro;
    private javax.swing.JTextField txtValorHora;
    private javax.swing.ButtonGroup vagasBtnGroup;
    // End of variables declaration//GEN-END:variables
private Cliente retornaCliente(){
        String nome = txtNomeClienteCadastro.getText();
        String email = txtEmailClienteCadastro.getText();
        String telefone = txtTelefoneClienteCadastro.getText();
        
        Cliente c = new Cliente();
        c.setNome(nome);
        c.setEmail(email);
        c.setTelefone(telefone);
        return c;
    }
private Veiculo retornaVeiculo(){
        String placa = txtPlacaVeiculoCadastro.getText();
        String modelo = txtModeloVeiculoCadastro.getText();
        String cor = txtCorVeiculoCadastro.getText();
        
        if(this.clienteSelecionado == null){
            JOptionPane.showMessageDialog(this, "Não foi selecionado nenhum cliente", "ERRO", JOptionPane.WARNING_MESSAGE);
            return null;
        }
        
        Veiculo v = new Veiculo();
        v.setCor(cor);
        v.setModelo(modelo);
        v.setPlaca(placa);
        
        v.setCliente(this.clienteSelecionado);
        return v;
    }
private Operacao retornaOperacao(){
    double precoHora = Double.parseDouble(txtValorHora.getText());
    Operacao op = new Operacao();

    if(linhaSelecionada > -1 && this.op != null){
        op.setHorarioEntrada(this.op.getHorarioEntrada());
    }else{
        op.setHorarioEntrada(LocalDateTime.now());
    }
    op.setVeiculo(veiculoSelecionado);
    op.setValorHora(precoHora);
    op.getId_operacao();
    return op;
}
public void preencherCliente(Cliente c){
        this.clienteSelecionado = c;
        txtNomeClienteVeiculo.setText(c.getNome());
    }
public void preencherVeiculo(Veiculo v){
        this.veiculoSelecionado = v;
        txtPlacaOp.setText(v.getPlaca());
        txtModeloOp.setText(v.getModelo());
        txtCorOp.setText(v.getCor());
        txtNomeClienteOp.setText(v.getCliente().getNome());
    }
public void limparCamposCliente() {
    txtNomeClienteCadastro.setText("");
    txtEmailClienteCadastro.setText("");
    txtTelefoneClienteCadastro.setText("");

    }
public void limparCamposVeiculo() {
    txtPlacaVeiculoCadastro.setText("");
    txtModeloVeiculoCadastro.setText("");
    txtCorVeiculoCadastro.setText("");
    txtNomeClienteVeiculo.setText(""); 

    this.clienteSelecionado = null; 

    }

public void limparCamposOperacao(){
    txtPlacaOp.setText("");
        txtModeloOp.setText("");
        txtCorOp.setText("");
        txtNomeClienteOp.setText("");
}

public final void preencheCbxVaga(){
    cbxVagas.removeAllItems();

    for (Vaga v : vgc.listarVagas()) {
        if (v.isStatus() == false) {
            cbxVagas.addItem(v);
        }
    }
    }
public void atualizarTabelaClientes(String busca) {
        DefaultTableModel model = (DefaultTableModel) tblClientesPrincipal.getModel();
        model.setNumRows(0);

        List<Cliente> clientes = cc.filtrarClientes(busca);

        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getTelefone()
            });
        }
}
public void atualizarTabelaVeiculos(String busca) {
   
        DefaultTableModel model = (DefaultTableModel) tblCadastroVeiculos.getModel();
        model.setRowCount(0);

        try{
            List<Veiculo> veiculos = vc.filtrarVeiculos(busca);
 

            for (com.luizfrancisco.estacionamento.model.Veiculo v : veiculos) {
                model.addRow(new Object[]{
                    v.getId(),
                    v.getPlaca(),
                    v.getModelo(),
                    v.getCor(),
                    v.getCliente().getNome() 
                });
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, 
            "Erro ao carregar dados do veículo: " + e.getMessage(),
            "Erro", 
            JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
private void atualizarTabelaOperacoes(String busca) {

        DefaultTableModel model = (DefaultTableModel) tblOperacao.getModel();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
        model.setRowCount(0);
        List<Operacao> listaOperacoes;
        listaOperacoes = oc.filtrarOperacoes(busca);

        for (Operacao op : listaOperacoes) {
            
            String entradaFormatada = (op.getHorarioEntrada() != null) ? op.getHorarioEntrada().format(dtf) : "";
            String saidaFormatada = (op.getHorarioSaida() != null) ? op.getHorarioSaida().format(dtf) : "Em andamento...";
            
            model.addRow(new Object[]{
                op.getId_operacao(),
                op.getVaga().getId(),
                op.getVeiculo().getPlaca(),
                entradaFormatada,
                saidaFormatada,
                op.getValorTotal()
            });
        }
    }
private void atualizarTabelaVagas(String buscaId) {
       
        DefaultTableModel model = (DefaultTableModel) tblVagas.getModel();
        model.setRowCount(0);
        
        String statusFiltro = "TODAS";
        if(rdbLivre.isSelected()) statusFiltro = "LIVRE";
        else if (rdbOcupada.isSelected()) statusFiltro = "OCUPADA";
        List<Vaga> vagas = vgc.filtrarVagas(buscaId, statusFiltro);

       
        for (Vaga v : vagas) {
            String status = (v.isStatus()) ? "OCUPADA" : "LIVRE"; 
            model.addRow(new Object[]{
                v.getId(),
                status 
            });
        }
    }

private void atualizarPainelDadosOperacao(Operacao op) {
    
        if (op == null) {
            lblDadosCodigo.setText("-");
            lblDadosCodigoOp.setText("-");
            lblDadosEntrada.setText("-");
            lblDadosSaida.setText("-");
            lblDadosValorTotal.setText("-");
            return;
        }

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        if (op.getVaga() != null) {
            lblDadosCodigo.setText(String.valueOf(op.getVaga().getId()));
        }
    
                lblDadosCodigoOp.setText(String.valueOf(op.getId_operacao()));
    
        if (op.getHorarioEntrada() != null) {
            lblDadosEntrada.setText(op.getHorarioEntrada().format(dtf));
        }

 
        if (op.getHorarioSaida() == null) {
            lblDadosSaida.setText("Em andamento...");
            lblDadosValorTotal.setText("..."); 
        }else {
 
            lblDadosSaida.setText(op.getHorarioSaida().format(dtf));
            lblDadosValorTotal.setText(String.format("R$ %.2f", op.getValorTotal()));
        }
    }

private void gerarRelatorio(String tipo){
    try {
        String caminho = "/relatorios/" + tipo + ".jasper";
            
        Connection con = Conexao.getConnection();
            
        Map<String, Object> parametros = new HashMap<>();
            
        RelatorioUtil.abrirPDF(caminho, parametros, con);
    } catch (Exception e) {
        e.printStackTrace();
    }
  }

private void configurarListeners() {
    tblOperacao.getSelectionModel().addListSelectionListener(e -> {     
        if (!e.getValueIsAdjusting() && tblOperacao.getSelectedRow() != -1) {      
            int linha = tblOperacao.getSelectedRow();
            int id = (int) tblOperacao.getValueAt(linha, 0);
            atualizarEstadoBotaoFinalizar(id);
        }
    });
}


private void atualizarEstadoBotaoFinalizar(int idOperacao) {
    Operacao opVerificacao = oc.buscarOp(idOperacao);

    if (opVerificacao.getHorarioSaida() == null) {
       
        btnFinalizarOp.setEnabled(true);
        btnFinalizarOp.setBackground(new Color(34, 139, 34));
        btnFinalizarOp.setForeground(Color.WHITE);
    } else {
       
        btnFinalizarOp.setEnabled(false);
        btnFinalizarOp.setBackground(Color.LIGHT_GRAY); 
        btnFinalizarOp.setForeground(Color.DARK_GRAY);
    }
}

}
